### ISSUE TITLE
Instagram force closes

### ISSUE THREAD

**Issue by punitpi** [iHelp101/XInsta#34]
when scrolled down it force closes

**Comment by iHelp101** [comment]
I updated the hooks recently. Are you still having this issue? Or is it resolved? Thank you.

**Comment by punitpi** [comment]
It wasn't there yesterday!! It started today like 3-4 hours back

**Comment by iHelp101** [comment]
Can you attach your Xposed or XInsta error log? I wonder if you have a version of Instagram that in not on APKMirror yet.

**Comment by punitpi** [comment]
`      
[04-12 22:51:39.118 841:8363 E/AnalyticsUploader]
error in uploading the analytic file
com.instagram.common.p.f.a: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused)
	at com.instagram.common.p.f.q.onError(:203484)
	at com.facebook.proxygen.JniHandler.onError(:73552)
	at com.facebook.proxygen.EventBase.loopForever(Native Method)
	at com.facebook.proxygen.HTTPThread.run(:73481)
	at com.instagram.common.p.f.g.run(:203016)
	at java.lang.Thread.run(Thread.java:764)

[04-12 22:51:39.163 841:841 I/chatty]
uid=10103(com.instagram.android) identical 6 lines

[04-12 22:51:39.170 841:8401 E/AnalyticsUploader]
error in uploading the analytic file
com.instagram.common.p.f.a: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused)
	at com.instagram.common.p.f.q.onError(:203484)
	at com.facebook.proxygen.JniHandler.onError(:73552)
	at com.facebook.proxygen.EventBase.loopForever(Native Method)
	at com.facebook.proxygen.HTTPThread.run(:73481)
	at com.instagram.common.p.f.g.run(:203016)
	at java.lang.Thread.run(Thread.java:764)

[04-12 22:51:39.285 841:841 I/chatty]
uid=10103(com.instagram.android) identical 2 lines

[04-12 22:51:39.290 841:841 I/zygote]
Deoptimizing java.lang.String com.instagram.common.util.y.a(java.lang.String, java.util.Collection) due to JIT inline cache

[04-12 22:51:39.296 1635:6368 I/ActivityManager]
Start proc 8455:com.instagram.android:browser/u0a103 for service com.instagram.android/com.facebook.browser.lite.BrowserLiteIntentService

[04-12 22:51:39.406 8455:8455 I/Xposed]
XInsta - Instagram Version Code: 102221279

[04-12 22:51:39.406 8455:8455 I/System.out]
Set Error: Instagram Version Code: 102221279

[04-12 22:51:39.556 8461:8461 W/com.instagram.android]
type=1400 audit(0.0:9909): avc: denied { read } for comm=4A69742074687265616420706F6F6C name="uptime" dev="proc" ino=4026532112 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:proc:s0 tclass=file permissive=0

[04-12 22:51:39.784 8480:8480 F/DEBUG]
pid: 841, tid: 858, name: Jit thread pool  >>> com.instagram.android <<<

[04-12 22:51:39.917 8455:8455 E/b]
Skipping ANR Detector for process: com.instagram.android:browser

[04-12 22:51:41.170 1635:8518 W/ActivityManager]
  Force finishing activity com.instagram.android/.activity.MainTabActivity

[04-12 22:51:41.185 1635:2239 I/ActivityManager]
Showing crash dialog for package com.instagram.android u0

[04-12 22:51:41.187 1635:2238 D/RestartProcessManager]
increase duration : 7484 for com.instagram.android

[04-12 22:51:41.247 1635:2300 W/InputDispatcher]
channel 'b291c15 AtchDlg:com.instagram.android/com.instagram.mainactivity.ActivityInTab (server)' ~ Consumer closed input channel or an error occurred.  events=0x9

[04-12 22:51:41.247 1635:2300 E/InputDispatcher]
channel 'b291c15 AtchDlg:com.instagram.android/com.instagram.mainactivity.ActivityInTab (server)' ~ Channel is unrecoverably broken and will be disposed!

[04-12 22:51:41.247 1635:2300 W/InputDispatcher]
channel '43e9fff com.instagram.android/com.instagram.android.activity.MainTabActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0xd

[04-12 22:51:41.247 1635:2300 E/InputDispatcher]
channel '43e9fff com.instagram.android/com.instagram.android.activity.MainTabActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

[04-12 22:51:41.252 1635:4023 D/EmbryoManager]
prepare com.instagram.android user 0

[04-12 22:51:41.252 1635:4016 I/WindowManager]
WIN DEATH: Window{43e9fff u0 com.instagram.android/com.instagram.android.activity.MainTabActivity}

[04-12 22:51:41.252 1635:4023 I/ActivityManager]
Process com.instagram.android (pid 841) has died: vis  +99TOP 

[04-12 22:51:41.252 1635:4016 W/InputDispatcher]
Attempted to unregister already unregistered input channel '43e9fff com.instagram.android/com.instagram.android.activity.MainTabActivity (server)'

[04-12 22:51:41.252 1635:4016 W/InputDispatcher]
Attempted to unregister already unregistered input channel 'b291c15 AtchDlg:com.instagram.android/com.instagram.mainactivity.ActivityInTab (server)'

[04-12 22:51:41.254 1635:4023 D/ActivityManager]
Process com.instagram.android has 0 services

[04-12 22:51:42.677 1635:8518 W/ActivityManager]
Ignoring remove of inactive process: ProcessRecord{81718da 0:com.instagram.android/u0a103}

[04-12 22:51:44.267 1635:2237 I/ActivityManager]
Start proc 8559:com.instagram.android/u0a103 for embryo com.instagram.android

[04-12 22:51:44.267 1635:2237 D/Embryo_Uterus]
Embryo created.com.instagram.android, pid=8559

[04-12 22:51:44.338 8559:8571 W/XSharedPreferences]
hasFileChanged
java.io.IOException: Operation not permitted while reading /data/data/com.sudocode.sudohide/shared_prefs/com.sudocode.sudohide_preferences.xml
	at de.robv.android.xposed.services.ZygoteService.statFile(Native Method)
	at de.robv.android.xposed.XSharedPreferences.hasFileChanged(XSharedPreferences.java:175)
	at de.robv.android.xposed.XSharedPreferences.reload(XSharedPreferences.java:164)
	at com.sudocode.sudoHideModule.XposedMain.modifyHookedMethodArguments(XposedMain.java:163)
	at com.sudocode.sudoHideModule.XposedMain.access$100(XposedMain.java:27)
	at com.sudocode.sudoHideModule.XposedMain$2.beforeHookedMethod(XposedMain.java:105)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
	at android.app.ApplicationPackageManager.getPackageInfo(<Xposed>)
	at com.ihelp101.instagram.Module.handleLoadPackage(Module.java:1514)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
	at de.robv.android.xposed.XposedInit$5.afterHookedMethod(XposedInit.java:213)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:375)
	at android.app.LoadedApk.<init>(<Xposed>)
	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2251)
	at android.app.ActivityThread.getPackageInfoNoCheck(ActivityThread.java:2212)
	at android.app.ActivityThread$ApplicationThread.schedulePreload(ActivityThread.java:1493)
	at android.app.IApplicationThread$Stub.onTransact(IApplicationThread.java:1092)
	at android.os.Binder.execTransact(Binder.java:692)

[04-12 22:51:44.363 8559:8571 I/Xposed]
XInsta - Instagram Version Code: 102221279

[04-12 22:51:44.363 8559:8571 I/System.out]
Set Error: Instagram Version Code: 102221279

[04-12 22:51:44.370 8559:8571 W/XSharedPreferences]
hasFileChanged
java.io.IOException: Operation not permitted while reading /data/data/com.sudocode.sudohide/shared_prefs/com.sudocode.sudohide_preferences.xml
	at de.robv.android.xposed.services.ZygoteService.statFile(Native Method)
	at de.robv.android.xposed.XSharedPreferences.hasFileChanged(XSharedPreferences.java:175)
	at de.robv.android.xposed.XSharedPreferences.reload(XSharedPreferences.java:164)
	at com.sudocode.sudoHideModule.XposedMain.modifyHookedMethodArguments(XposedMain.java:163)
	at com.sudocode.sudoHideModule.XposedMain.access$100(XposedMain.java:27)
	at com.sudocode.sudoHideModule.XposedMain$2.beforeHookedMethod(XposedMain.java:105)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
	at android.app.ApplicationPackageManager.getPackageInfo(<Xposed>)
	at com.ihelp101.instagram.Module.handleLoadPackage(Module.java:1527)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
	at de.robv.android.xposed.XposedInit$5.afterHookedMethod(XposedInit.java:213)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:375)
	at android.app.LoadedApk.<init>(<Xposed>)
	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2251)
	at android.app.ActivityThread.getPackageInfoNoCheck(ActivityThread.java:2212)
	at android.app.ActivityThread$ApplicationThread.schedulePreload(ActivityThread.java:1493)
	at android.app.IApplicationThread$Stub.onTransact(IApplicationThread.java:1092)
	at android.os.Binder.execTransact(Binder.java:692)

[04-12 22:51:44.410 8559:8571 W/XSharedPreferences]
hasFileChanged
java.io.IOException: Operation not permitted while reading /data/data/com.sudocode.sudohide/shared_prefs/com.sudocode.sudohide_preferences.xml
	at de.robv.android.xposed.services.ZygoteService.statFile(Native Method)
	at de.robv.android.xposed.XSharedPreferences.hasFileChanged(XSharedPreferences.java:175)
	at de.robv.android.xposed.XSharedPreferences.reload(XSharedPreferences.java:164)
	at com.sudocode.sudoHideModule.XposedMain.modifyHookedMethodResult(XposedMain.java:177)
	at com.sudocode.sudoHideModule.XposedMain.access$200(XposedMain.java:27)
	at com.sudocode.sudoHideModule.XposedMain$4.afterHookedMethod(XposedMain.java:123)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:375)
	at android.app.ApplicationPackageManager.getInstalledPackages(<Xposed>)
	at com.ihelp101.instagram.Module.startHooks(Module.java:4377)
	at com.ihelp101.instagram.Module.handleLoadPackage(Module.java:1580)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
	at de.robv.android.xposed.XposedInit$5.afterHookedMethod(XposedInit.java:213)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:375)
	at android.app.LoadedApk.<init>(<Xposed>)
	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2251)
	at android.app.ActivityThread.getPackageInfoNoCheck(ActivityThread.java:2212)
	at android.app.ActivityThread$ApplicationThread.schedulePreload(ActivityThread.java:1493)
	at android.app.IApplicationThread$Stub.onTransact(IApplicationThread.java:1092)
	at android.os.Binder.execTransact(Binder.java:692)

[04-12 22:51:44.416 8455:8485 E/b]
Failed to send crash attachment report /data/user/0/com.instagram.android/app_minidumps/6bea03594b35c87301b8fb98d0bf1222.dmp
com.facebook.acra.d.d: Error while sending report to Http Post Form.
	at com.facebook.acra.d.b.a(:35391)
	at com.facebook.acra.r.r$0(:37022)
	at com.facebook.acra.r.a(:36541)
	at com.facebook.acra.r.a(:36451)
	at com.facebook.acra.r.a(:36516)
	at com.facebook.acra.q.a(:36313)
	at com.facebook.acra.q.run(:36338)
Caused by: java.net.SocketTimeoutException: timeout
	at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)
	at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:261)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(Unknown Source:0)
	at com.facebook.acra.d.b.a(:35385)
	... 6 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:741)
	at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	... 19 more

[04-12 22:51:44.515 8559:8571 W/XSharedPreferences]
hasFileChanged
java.io.IOException: Operation not permitted while reading /data/data/com.sudocode.sudohide/shared_prefs/com.sudocode.sudohide_preferences.xml
	at de.robv.android.xposed.services.ZygoteService.statFile(Native Method)
	at de.robv.android.xposed.XSharedPreferences.hasFileChanged(XSharedPreferences.java:175)
	at de.robv.android.xposed.XSharedPreferences.reload(XSharedPreferences.java:164)
	at com.sudocode.sudoHideModule.XposedMain.modifyHookedMethodResult(XposedMain.java:177)
	at com.sudocode.sudoHideModule.XposedMain.access$200(XposedMain.java:27)
	at com.sudocode.sudoHideModule.XposedMain$4.afterHookedMethod(XposedMain.java:123)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:375)
	at android.app.ApplicationPackageManager.getInstalledPackages(<Xposed>)
	at com.ihelp101.instagram.Module.startHooks(Module.java:4661)
	at com.ihelp101.instagram.Module.handleLoadPackage(Module.java:1580)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
	at de.robv.android.xposed.XposedInit$5.afterHookedMethod(XposedInit.java:213)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:375)
	at android.app.LoadedApk.<init>(<Xposed>)
	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2251)
	at android.app.ActivityThread.getPackageInfoNoCheck(ActivityThread.java:2212)
	at android.app.ActivityThread$ApplicationThread.schedulePreload(ActivityThread.java:1493)
	at android.app.IApplicationThread$Stub.onTransact(IApplicationThread.java:1092)
	at android.os.Binder.execTransact(Binder.java:692)

[04-12 22:51:44.811 8559:8559 D/Embryo]
preload com.instagram.android, 76ms, hwui=true, layout=true, decor=false

[04-12 22:52:52.332 1635:2237 D/Embryo_Uterus]
rank:55, com.instagram.android, 849193

[04-12 22:53:48.710 8559:8559 W/XSharedPreferences]
hasFileChanged
java.io.IOException: Operation not permitted while reading /data/data/com.sudocode.sudohide/shared_prefs/com.sudocode.sudohide_preferences.xml
	at de.robv.android.xposed.services.ZygoteService.statFile(Native Method)
	at de.robv.android.xposed.XSharedPreferences.hasFileChanged(XSharedPreferences.java:175)
	at de.robv.android.xposed.XSharedPreferences.reload(XSharedPreferences.java:164)
	at com.sudocode.sudoHideModule.XposedMain.modifyHookedMethodArguments(XposedMain.java:163)
	at com.sudocode.sudoHideModule.XposedMain.access$100(XposedMain.java:27)
	at com.sudocode.sudoHideModule.XposedMain$2.beforeHookedMethod(XposedMain.java:105)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
	at android.app.ApplicationPackageManager.getPackageInfo(<Xposed>)
	at com.ihelp101.instagram.Module$VersionCheck.onPostExecute(Module.java:845)
	at com.ihelp101.instagram.Module$VersionCheck.onPostExecute(Module.java:816)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6809)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

[04-12 22:55:12.737 10990:10990 D/MyDeviceLogs]
[LogcatLiveFragment] onSearchAction: Instagram

[04-12 22:55:41.063 1635:2856 I/ActivityManager]
START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.instagram.android/.activity.MainTabActivity bnds=[699,1242][848,1412] (has extras)} from uid 10102 pid 3921

[04-12 22:55:41.291 1635:2238 D/RestartProcessManager]
Update Total Launch Times :com.instagram.android

[04-12 22:55:41.291 1635:2238 D/RestartProcessManager]
updateSelf :  com.instagram.android, size : 30

[04-12 22:55:41.291 1635:2238 D/RestartProcessManager]
Increase Total Launch Time : com.instagram.android, times : 27, index : 29

[04-12 22:55:41.291 1635:2238 D/RestartProcessManager]
Last Running Package : com.instagram.android , start time 1523553941291

[04-12 22:55:41.292 1635:3034 D/EmbryoManager]
Embryo claimed. com.instagram.android, pid=8559

[04-12 22:55:41.311 8559:8559 I/Xposed]
XInsta - Instagram Version Code: 102221279

[04-12 22:55:41.311 8559:8559 I/System.out]
Set Error: Instagram Version Code: 102221279

[04-12 22:55:41.594 8559:8559 E/b]
Initializing ANR detector for process: com.instagram.android

[04-12 22:55:41.758 8559:11548 I/zygote]
Thread[22,tid=11548,Native,Thread*=0xca711a00,peer=0x13081128,"IgExecutor #3"] recursive attempt to load library "/data/app/com.instagram.android-l-iIJPHP6eM3GxjIrXeTgg==/lib/arm/libfb.so"

[04-12 22:55:41.867 8559:8559 I/chatty]
uid=10103(com.instagram.android) identical 14 lines

[04-12 22:55:41.900 8559:8559 I/chatty]
uid=10103(com.instagram.android) identical 4 lines

[04-12 22:55:41.930 8559:8559 I/chatty]
uid=10103(com.instagram.android) identical 6 lines

[04-12 22:55:41.940 8559:8559 I/chatty]
uid=10103(com.instagram.android) identical 4 lines

[04-12 22:55:41.980 8559:8559 I/chatty]
uid=10103(com.instagram.android) identical 16 lines

[04-12 22:55:41.997 8559:8559 I/chatty]
uid=10103(com.instagram.android) identical 6 lines

[04-12 22:55:42.078 8559:8559 I/chatty]
uid=10103(com.instagram.android) identical 4 lines

[04-12 22:55:42.125 8559:8559 I/chatty]
uid=10103(com.instagram.android) identical 6 lines

[04-12 22:55:42.197 1635:2246 I/ActivityManager]
Displayed com.instagram.android/.activity.MainTabActivity: +903ms (total +3s275ms)

[04-12 22:55:42.308 8559:8559 D/LocationManager]
requestLocationUpdates listener=com.instagram.location.a.c@5e6374e packageName= com.instagram.android

[04-12 22:55:42.309 1635:25842 E/LocationManagerService]
requestLocationUpdates: uid=10103, pid=8559, provider=passive, package=com.instagram.android listener= android.location.ILocationListener$Stub$Proxy@6808a61 intent= null

[04-12 22:55:42.359 8559:8559 I/chatty]
uid=10103(com.instagram.android) identical 12 lines

[04-12 22:55:42.387 8559:8559 I/chatty]
uid=10103(com.instagram.android) identical 2 lines

[04-12 22:55:43.476 8559:8559 I/chatty]
uid=10103(com.instagram.android) identical 18 lines

[04-12 22:55:43.587 8559:8559 I/zygote]
Deoptimizing boolean com.instagram.common.q.c.b(com.instagram.common.q.a) due to JIT inline cache

[04-12 22:55:43.606 8559:11545 E/AnalyticsUploader]
error in uploading the analytic file
com.instagram.common.p.f.a: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused)
	at com.instagram.common.p.f.q.onError(:203484)
	at com.facebook.proxygen.JniHandler.onError(:73552)
	at com.facebook.proxygen.EventBase.loopForever(Native Method)
	at com.facebook.proxygen.HTTPThread.run(:73481)
	at com.instagram.common.p.f.g.run(:203016)
	at java.lang.Thread.run(Thread.java:764)

[04-12 22:55:43.683 8559:11665 E/AnalyticsUploader]
error in uploading the analytic file
com.instagram.common.p.f.a: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused)
	at com.instagram.common.p.f.q.onError(:203484)
	at com.facebook.proxygen.JniHandler.onError(:73552)
	at com.facebook.proxygen.EventBase.loopForever(Native Method)
	at com.facebook.proxygen.HTTPThread.run(:73481)
	at com.instagram.common.p.f.g.run(:203016)
	at java.lang.Thread.run(Thread.java:764)

[04-12 22:55:43.906 1635:2292 V/AlarmManager]
Triggering alarm #0: 3 when =5000 package =com.instagram.android operation =*alarm*:com.instagram.android/com.facebook.fbreact.autoupdater.ighttp.IgHttpUpdateService flags =0x0

[04-12 22:55:44.099 8559:8559 I/zygote]
Deoptimizing boolean com.instagram.common.q.c.b(com.instagram.common.q.a) due to JIT inline cache

[04-12 22:55:44.308 8559:8559 I/zygote]
Deoptimizing boolean com.instagram.common.q.c.b(com.instagram.common.q.a) due to JIT inline cache

[04-12 22:55:44.337 8559:11658 W/ServiceInfoParser]
com.facebook.common.t.a.r: Service com.instagram.contacts.ccu.intf.CCUJobService is missing meta key com.facebook.common.jobscheduler.compat.jobIds

[04-12 22:55:44.337 8559:11658 W/ServiceInfoParser]
com.facebook.common.t.a.r: Service com.instagram.lazyload.download.ModuleDownloadJobService is missing meta key com.facebook.common.jobscheduler.compat.jobIds

[04-12 22:55:44.337 8559:11658 W/ServiceInfoParser]
com.facebook.common.t.a.r: Service com.instagram.pendingmedia.service.uploadretrypolicy.UploadRetryJobService is missing meta key com.facebook.common.jobscheduler.compat.jobIds

[04-12 22:55:44.337 8559:11658 W/ServiceInfoParser]
com.facebook.common.t.a.r: Service com.instagram.pendingmedia.service.uploadretrypolicy.UploadJobService is missing meta key com.facebook.common.jobscheduler.compat.jobIds

[04-12 22:55:44.337 8559:11658 W/ServiceInfoParser]
com.facebook.common.t.a.r: Service com.instagram.util.offline.BackgroundWifiPrefetcherJobService is missing meta key com.facebook.common.jobscheduler.compat.jobIds

[04-12 22:55:45.118 8559:8559 I/chatty]
uid=10103(com.instagram.android) identical 2 lines

[04-12 22:55:45.192 8559:8559 I/chatty]
uid=10103(com.instagram.android) identical 2 lines

[04-12 22:55:45.205 8559:11664 E/AnalyticsUploader]
error in uploading the analytic file
com.instagram.common.p.f.a: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused)
	at com.instagram.common.p.f.q.onError(:203484)
	at com.facebook.proxygen.JniHandler.onError(:73552)
	at com.facebook.proxygen.EventBase.loopForever(Native Method)
	at com.facebook.proxygen.HTTPThread.run(:73481)
	at com.instagram.common.p.f.g.run(:203016)
	at java.lang.Thread.run(Thread.java:764) ` 


this is small portion of the log

**Comment by punitpi** [comment]
and the version on my phone was updated 2 days ago and there is a updated version on apkmirror

**Comment by iHelp101** [comment]
Can you get me the Instagram version code? In your Xposed log it will say "Instagram Version Code: XXXXXXXX". That way I can install this version on my device and do some testing.

**Comment by punitpi** [comment]
-12 22:55:52.248 I/Xposed  (11764): XInsta - XInsta Initialized
04-12 22:55:52.266 I/Xposed  (11764): XInsta - Instagram Version Code: 102221279
04-12 22:55:52.274 I/Xposed  (11764): XInsta - Device Codename: ONEPLUS A5000
04-12 22:55:52.281 I/Xposed  (11764): XInsta - Android Version: 8.0.0
04-12 22:55:52.286 E/Xposed  (11764): Zygote service is not accessible from PID 11764, UID 10103
04-12 22:55:52.288 E/Xposed  (11764): Zygote service is not accessible from PID 11764, UID 10103
04-12 22:55:52.293 I/Xposed  (11764): XInsta - XInsta Version 2.0.4

**Comment by iHelp101** [comment]
I just tested this version and I am having no issues. Can you disable SudoHide, reboot, and see if you still face the issue? Most of the crashes I am seeing an related to HTTP request failing, which XInsta doesn't complete unless downloading a post, icon, etc.

**Comment by punitpi** [comment]
I have already uninstalled sudo hide and restarted the phone

**Comment by yazanjamous** [comment]
Profile pic zoom not working now!

**Comment by iHelp101** [comment]
@yazanjamous I am aware of this issue. They removed an unofficial API, which was my worry. I am looking for a solution.

https://www.instagram.com/natgeo/?__a=1

**Comment by iHelp101** [comment]
@punitpi I am looking further into this. Is there any chance you can get me a logcat of the crash? That will allow me to see the exact piece of code causing the crash.

**Comment by yazanjamous** [comment]
@iHelp101 im also developer 

instagram banned https://www.instagram.com/username/?__a=1
but will work after a few hrs but also will banned api again same yesterday

see this post
https://later.com/blog/instagram-api/

**Comment by iHelp101** [comment]
@yazanjamous Yup, it was an unofficial API. The previous was https://www.instagram.com/username/media. I received an email regarding this about a week ago from Instagram. I was hoping this unofficial API would fall under one of the listed public content or basic endpoints, but this of course was not an official endpoint. It appears this feature is going to be very difficult to fix if possible to fix. 

Public Content - all remaining capabilities to read public media on a user's behalf on December 11, 2018
Basic - to read a user’s own profile info and media in early 2020

**Comment by yazandev** [comment]
@iHelp101 but we can find the url from instagram app without use api

eximple :     
invoke-virtual {v1, v0}, Lcom/instagram/common/ui/widget/imageview/IgImageView;->setUrl(Ljava/lang/String;)V

this url but not hd .. but can find hd if search..

**Comment by iHelp101** [comment]
@yazandev Instagram only serves their profile icons in 150x150 (Rare cases 300x300 for certain tablets). They never serve a full resolution profile icon (1080x1080) that I have seen. All URLs are verified by signatures, so you can't request different sizes.

**Comment by yazandev** [comment]
@iHelp101 yes but from 2 years i was use this
string.replace("/s150x150", "").replace("s150x150/", "");

and was works! but now no!

**Comment by woeijiunn88** [comment]
FC occured again now when scrolling down the instagram posts, you may test it. @iHelp101

**Comment by iHelp101** [comment]
Which Instagram version are you using? I know one of the alpha versions has a bug where if you had a multi-post on screen is crashed Instagram.

**Comment by woeijiunn88** [comment]
v47.0.0.16.96

**Comment by woeijiunn88** [comment]
ya when on multi-post it crashed =/

**Comment by iHelp101** [comment]
Disable XInsta (Open Xposed -> Three Line Icon -> Modules -> Uncheck XInsta) and reboot. Please verify if the issue occurs with XInsta disabled. In my testing this is a Instagram issue and not an XInsta issue.

**Comment by woeijiunn88** [comment]
Ya, i tested just now LOL.
Same as Instagram self issue.
😶😶😶

**Comment by iHelp101** [comment]
I reported the bug to Instagram a few days ago when I noticed it in an alpha version. It is strange the bug made it to what looks like a stable release.

**Comment by woeijiunn88** [comment]
Hmm we just wait for future alpha release then =/

**Comment by woeijiunn88** [comment]
After cleared my Instagram's data, i didn't faced any fc again lol.
